sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

# Admins

services:
    admin.event:
        class: App\Admin\EventAdmin
        autowire: true
        tags:
            - { name: sonata.admin, model_class: App\Entity\Event, manager_type: orm, label: Events, group: Entities }

    admin.image:
        class: App\Admin\ImageAdmin
        arguments:
            $uploadsBucket: '%env(UPLOADS_BUCKET)%'
            $cloudfrontUrl: '%env(UPLOADS_CLOUDFRONT_URL)%'
        autowire: true
        tags:
            - { name: sonata.admin, model_class: App\Entity\Image, manager_type: orm, label: Images, group: Entities }
