version: '3'
services:
  php:
    container_name: photowalkboston
    build: .
    ports:
      - "8081:8000"
    command: "php"
    volumes:
      - .:/var/task

  mysql:
    container_name: photowalkboston-mysql
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photowalkboston
      MYSQL_USER: photowalkboston
      MYSQL_PASSWORD: photowalkboston

volumes:
  db_data: {}
