# Read the documentation at https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: photowalkboston
frameworkVersion: ^3.16.0

provider:
  name: aws
  # The AWS region in which to deploy (us-east-1 is the default)
  region: us-east-1
  # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
  stage: dev
  runtime: provided.al2
  environment:
    # Symfony environment variables
    APP_ENV: dev
  vpc:
    securityGroupIds:
      - ${cf:vpc.LambdaSecurityGroup}
      - ${cf:filesystem-${opt:stage}.EfsSecurityGroup}
    subnetIds:
      - ${cf:vpc.PublicSubnet1}
      - ${cf:vpc.PublicSubnet2}

plugins:
  - ./vendor/bref/bref
  - serverless-lift

functions:
  # This function runs the Symfony website/API
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - httpApi: '*'
    fileSystemConfig:
      localMountPath: "/mnt/sqlite"
      arn: ${cf:filesystem-${opt:stage}.FilesystemAccessPointArn}

  # This function let us run console commands in Lambda
  console:
    handler: bin/console
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-82} # PHP
      - ${bref:layer.console} # The "console" layer
    fileSystemConfig:
      localMountPath: "/mnt/sqlite"
      arn: ${cf:filesystem-${opt:stage}.FilesystemAccessPointArn}

constructs:
  website:
    type: server-side-website
    assets:
      '/bundles/*': public/bundles
      '/css/*': public/css
      '/iconic/*': public/iconic
      '/images/*': public/images
      '/js/*': public/js

package:
  patterns:
    # Excluded files and folders for deployment
    - '!assets/**'
    - '!node_modules/**'
    - '!public/build/**'
    - '!tests/**'
    - '!var/**'
    - '!config/aws/**'
    # If you want to include files and folders that are part of excluded folders,
    # add them at the end
    - 'var/cache/prod/**'
    - 'public/build/entrypoints.json'
    - 'public/build/manifest.json'
