Resources:

  Filesystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose

  FilesystemAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref Filesystem
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "0777"
        Path: /sqlite

  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue VpcId
      GroupDescription: "mnt target sg"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  FilesystemMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref Filesystem
      SecurityGroups:
        - !Ref EfsSecurityGroup
      SubnetId: !ImportValue PublicSubnet1

  FilesystemMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref Filesystem
      SecurityGroups:
        - !Ref EfsSecurityGroup
      SubnetId: !ImportValue PublicSubnet2

Outputs:
  FilesystemAccessPointArn:
    Value: !GetAtt FilesystemAccessPoint.Arn
  EfsSecurityGroup:
    Value: !Ref EfsSecurityGroup
