name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker compose
        run: docker compose up --build -d

      - name: Install packages
        run: docker exec photowalkboston bash -c "APP_ENV=prod composer install --no-progress --no-interaction --prefer-dist --no-dev"

      - name: Setup serverless framework
        run: npm i -g serverless@3

      - name: Deploy
        run: bin/deploy prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Migrate database
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: photowalkboston-prod-console
          Payload: '"doctrine:migrations:migrate --no-interaction"'
