name: CI/CD
on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      DATABASE_URL: mysql://photowalkboston:photowalkboston@0.0.0.0:3306/photowalkboston?serverVersion=8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: pcov
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 8.0
          mysql database: photowalkboston
          mysql user: photowalkboston
          mysql password: photowalkboston

      - name: Install composer packages
        run: composer install --no-progress --no-interaction --prefer-dist
      - name: Static analysis
        run: vendor/bin/phpstan
      - name: Database migrations
        run: bin/console doctrine:schema:update --force --dump-sql
      - name: Unit tests
        run: composer test
